### ISSUE TITLE
error in bin/bin_clcy.c:404:8: r_io_create_mem_map

### ISSUE THREAD

**Issue by askme765cs** [MaskRay/r2clemency#1]
I use manjaro 4.9.60-1-MANJARO,and I fail to install it,updating maybe neccesary

bin/bin_clcy.c: 在函数‘_patch_relocs’中:
bin/bin_clcy.c:404:8: 错误：提供给函数‘r_io_create_mem_map’的实参太少
  (void)r_io_create_mem_map (b->iob.io, &sec, NFO_VADDR, false);
        ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/libr/r_bin.h:6:0,
                 from bin/bin_clcy.c:2:
/usr/include/libr/r_io.h:485:12: 附注：在此声明
 R_API bool r_io_create_mem_map(RIO *io, RIOSection *sec, ut64 at, bool null, bool do_skyline);
            ^~~~~~~~~~~~~~~~~~~
make: *** [Makefile:28：bin/bin_clcy.o] 错误 1

**Comment by MaskRay** [comment]
Fixed with a6dee9026e67e7f7523de9573b0a248bfab568e8
